// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgwPeSGjx8H-tia9ekstJI1W9p01RWvQM',
    appId: '1:339894289327:web:ff7a5e768283cf9d32a55a',
    messagingSenderId: '339894289327',
    projectId: 'flutter-application-2024',
    authDomain: 'flutter-application-2024.firebaseapp.com',
    storageBucket: 'flutter-application-2024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJlsWmITeJVu2d1CEDJeopqoGp9BKIobE',
    appId: '1:339894289327:android:55a91579ef6818ff32a55a',
    messagingSenderId: '339894289327',
    projectId: 'flutter-application-2024',
    storageBucket: 'flutter-application-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUFiV61EBQwu1OT7C_11ip1SZJer2cnaM',
    appId: '1:339894289327:ios:8b89d1b06ff59f1832a55a',
    messagingSenderId: '339894289327',
    projectId: 'flutter-application-2024',
    storageBucket: 'flutter-application-2024.appspot.com',
    iosBundleId: 'com.example.flutterApplication2024',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUFiV61EBQwu1OT7C_11ip1SZJer2cnaM',
    appId: '1:339894289327:ios:8b89d1b06ff59f1832a55a',
    messagingSenderId: '339894289327',
    projectId: 'flutter-application-2024',
    storageBucket: 'flutter-application-2024.appspot.com',
    iosBundleId: 'com.example.flutterApplication2024',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgwPeSGjx8H-tia9ekstJI1W9p01RWvQM',
    appId: '1:339894289327:web:63a17d70183805ad32a55a',
    messagingSenderId: '339894289327',
    projectId: 'flutter-application-2024',
    authDomain: 'flutter-application-2024.firebaseapp.com',
    storageBucket: 'flutter-application-2024.appspot.com',
  );
}
